resolver: nightly-2018-04-04
flags:
  xmonad:
    testing: false
  xmobar:
    with_xft: true
    with_utf8: true
    with_dbus: true
    with_threaded: true
  xmonad-contrib:
    testing: false
    use_xft: true
extra-deps:
- dbus-1.0.1
- libxml-sax-0.7.5
- yeganesh-2.5
system-ghc: false
packages:
- xmobar/
- xmonad/
- xmonad-contrib/
