resolver: nightly-2018-01-29
flags:
  xmonad:
    testing: false
  xmobar:
    with_xft: true
    with_utf8: true
    with_dbus: true
    with_threaded: true
  xmonad-contrib:
    testing: false
    use_xft: true
extra-deps:
- dbus-0.10.13
- libxml-sax-0.7.5
- yeganesh-2.5
system-ghc: false
packages:
- xmobar/
- xmonad/
- xmonad-contrib/
